name: DamonIndustries
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8455513209299554
title: Damon Industries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C8C0'
    - '#000000'
    - '#707880'
    - '#000000'
    - '#000000'
  brandStrength: 0.6351754528908583
  lightness: 0.12522920912475066
  saturation: 0.8581730667410168
  rhythmicContrast: 0.4455631993144502
purpose:
  - name: null
    item: null
    url: null
